name: sync corestack provisioning template with s3
on: [ push ]
#  schedule:
#  - cron:  "*/15 * * * *"
#
jobs:
  s3-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: sync s3
      shell: bash
      env:
        aws_key_id: ${{ secrets.CORESTACK_CFN_S3_BUCKET_ACCESS_KEY}}
        aws_secret_access_key: ${{ secrets.CORESTACK_CFN_S3_BUCKET_SECRET_KEY }}
        aws_s3_bucket: ${{ secrets.S3_BUCKET }}
      run: |
        sudo apt-get update && sudo apt-get -y install awscli
        aws configure set aws_access_key_id $aws_key_id
        aws configure set aws_secret_access_key $aws_secret_access_key 
        aws configure set default.region us-east-1       
        aws s3 cp AWS/AWS_Onboarding_Templates/AWS_Onboarding_AllModule_AGTemplate.json s3://$aws_s3_bucket/
        aws s3api put-object-acl --bucket $aws_s3_bucket --key AWS_Onboarding_AllModule_AGTemplate.json  --acl public-read
        aws s3 cp AWS/AWS_Onboarding_Templates/AWS_Onboarding_AllModule_Template.json s3://$aws_s3_bucket/
        aws s3api put-object-acl --bucket $aws_s3_bucket --key AWS_Onboarding_AllModule_Template.json  --acl public-read
        aws s3 cp AWS/AWS_Onboarding_Templates/AWS_Onboarding_CloudopsBundle_Template.json s3://$aws_s3_bucket/
        aws s3api put-object-acl --bucket $aws_s3_bucket --key AWS_Onboarding_CloudopsBundle_Template.json  --acl public-read
        aws s3 cp AWS/AWS_Onboarding_Templates/AWS_Onboarding_FinopsBundle_Template.json s3://$aws_s3_bucket/
        aws s3api put-object-acl --bucket $aws_s3_bucket --key AWS_Onboarding_FinopsBundle_Template.json  --acl public-read
        aws s3 cp AWS/AWS_Onboarding_Templates/AWS_Onboarding_FinopsLimitedAccess_Template.json s3://$aws_s3_bucket/
        aws s3api put-object-acl --bucket $aws_s3_bucket --key AWS_Onboarding_FinopsLimitedAccess_Template.json  --acl public-read
        aws s3 cp AWS/AWS_Onboarding_Templates/AWS_Onboarding_SecopsBundle_Template.json s3://$aws_s3_bucket/
        aws s3api put-object-acl --bucket $aws_s3_bucket --key AWS_Onboarding_SecopsBundle_Template.json  --acl public-read
